# Generated by Django 3.0.7 on 2020-06-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0005_auto_20200615_1455'),
        ('apps_settings', '0011_sourceofincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_income', models.DateField()),
                ('amount', models.FloatField()),
                ('income_description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('source_of_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.SourceOfIncome')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expense', models.DateField()),
                ('amount', models.FloatField()),
                ('expense_description', models.TextField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('type_of_expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.TypeOfExpense')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
