# Generated by Django 3.0.7 on 2020-07-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200711_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source_of_income',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
