# Generated by Django 3.0.7 on 2020-07-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200715_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
