# Generated by Django 3.0.7 on 2020-07-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200715_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source_of_income',
            field=models.CharField(blank=True, choices=[('Transportation', 'Transportation'), ('Delivery', 'Delivery'), ('Other', 'Other'), ('Hiring', 'Hiring')], max_length=20, null=True),
        ),
    ]
