# Generated by Django 3.0.7 on 2020-07-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200715_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='type_of_expenses',
        ),
        migrations.AddField(
            model_name='expenses',
            name='type_of_expenditure',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Fuel', 'Fuel'), ('Repairs', 'Repairs'), ('General Servicing', 'General Servicing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source_of_income',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Delivery', 'Delivery'), ('Transportation', 'Transportation'), ('Hiring', 'Hiring')], max_length=20, null=True),
        ),
    ]
