# Generated by Django 3.0.7 on 2020-07-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200715_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='type_of_expenditure',
            field=models.CharField(blank=True, choices=[('Repairs', 'Repairs'), ('General Servicing', 'General Servicing'), ('Fuel', 'Fuel'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source_of_income',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Hiring', 'Hiring'), ('Delivery', 'Delivery'), ('Transportation', 'Transportation')], max_length=20, null=True),
        ),
    ]
