# Generated by Django 3.0.7 on 2020-07-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200715_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='type_of_expenditure',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('General Servicing', 'General Servicing'), ('Fuel', 'Fuel'), ('Repairs', 'Repairs')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source_of_income',
            field=models.CharField(blank=True, choices=[('Hiring', 'Hiring'), ('Transportation', 'Transportation'), ('Other', 'Other'), ('Delivery', 'Delivery')], max_length=20, null=True),
        ),
    ]
