# Generated by Django 3.0.7 on 2020-07-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200715_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='type_of_expenditure',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Fuel', 'Fuel'), ('Repairs', 'Repairs'), ('General Servicing', 'General Servicing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source_of_income',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Transportation', 'Transportation'), ('Hiring', 'Hiring'), ('Delivery', 'Delivery')], max_length=20, null=True),
        ),
    ]
