# Generated by Django 3.0.7 on 2020-06-15 17:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='format +222112233444', max_length=128, region=None),
        ),
    ]
