# Generated by Django 3.0.7 on 2020-06-15 17:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200615_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='format +233147258369', max_length=128, region=None),
        ),
    ]
