# Generated by Django 3.0.7 on 2020-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclefueltype',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiclepurpose',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiclestatus',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
