# Generated by Django 3.0.7 on 2020-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0002_auto_20200615_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclefueltype',
            name='fuel_type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclepurpose',
            name='purpose_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='vehicle_status',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
