# Generated by Django 3.0.7 on 2020-06-15 17:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200615_1704'),
        ('apps_settings', '0003_auto_20200615_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('phone_number_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_number_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('position', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProfile')),
            ],
        ),
    ]
