# Generated by Django 3.0.7 on 2020-06-15 17:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
