# Generated by Django 3.0.7 on 2020-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0011_sourceofincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceofincome',
            name='source_of_income',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='typeofexpense',
            name='type_of_expense',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclefueltype',
            name='fuel_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclepurpose',
            name='purpose_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='vehicle_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicle_type',
            field=models.CharField(max_length=20),
        ),
    ]
