# Generated by Django 3.0.7 on 2020-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_passenger_limit',
            field=models.IntegerField(),
        ),
    ]
