# Generated by Django 3.0.7 on 2020-06-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0001_initial'),
        ('vehicle', '0002_auto_20200615_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.VehicleFuelType'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.VehiclePurpose'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.VehicleStatus'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.VehicleType'),
        ),
    ]
