# Generated by Django 3.0.7 on 2020-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20200615_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
