# Generated by Django 3.0.7 on 2020-07-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20200615_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_cargo_limit',
            field=models.IntegerField(blank=True, help_text='weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Kerosine', 'Kerosine'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_passenger_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_purpose',
            field=models.CharField(blank=True, choices=[('Hiring', 'Hiring'), ('Transport', 'Transport'), ('Cargo', 'Cargo'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Salon', 'Solon'), ('Pick Up', 'Pick Up'), ('Mini Bus', 'Mini Bus'), ('Bus', 'Bus'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
